apiVersion: apps/v1
kind: Deployment
metadata:
  name: "react-ui"
  namespace: ms
  labels:
    app: "react-ui"
spec:
  selector:
    matchLabels:
      app: "react-ui"
  replicas: 1
  template:
    metadata:
      labels:
        app: "react-ui"
    spec:
      containers:
        - name: "react-ui"
          image: brkcd/ui
          ports:
            - containerPort: 8080
              name: "react-ui"
---
apiVersion: v1
kind: Service
metadata:
  name: "react-ui"
  namespace: ms
spec:
  selector:
    app: "react-ui"
  type: NodePort
  ports:
    - name: "react-ui"
      protocol: TCP
      port: 8080
      targetPort: 8080
      # If you set the `spec.type` field to `NodePort` and you want a specific port number 
