apiVersion: apps/v1
kind: Deployment
metadata:
  name: wish
  namespace: ms
  labels:
    app: wish
spec:
  selector:
    matchLabels:
      app: wish
  replicas: 1
  template:
    metadata:
      labels:
        app: wish
    spec:
      containers:
        - name: wish
          image: deekshithsn/wishlist
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: wish
  namespace: default
spec:
  selector:
    app: wish
  type: ClusterIP
  ports:
    - name: wish
      protocol: TCP
      port: 1003
      targetPort: 5000
