apiVersion: apps/v1
kind: Deployment
metadata:
  name: zui
  namespace: ms
  labels:
    app: zui
spec:
  selector:
    matchLabels:
      app: zui
  replicas: 1
  template:
    metadata:
      labels:
        app: zui
    spec:
      # initContainers:
      # Init containers are exactly like regular containers, except:
      # - Init containers always run to completion.
      # - Each init container must complete successfully before the next one starts.
      containers:
        - name: "zui-gateway"
          image: deekshithsn/zuul
          ports:
            - containerPort: 9999
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - react-ui
              topologyKey: topology.kubernetes.io/zone
---
apiVersion: v1
kind: Service
metadata:
  name: zui
  namespace: ms
spec:
  selector:
    app: zui
  type: NodePort
  ports:
    - name: zui
      protocol: TCP
      port: 9999
      targetPort: 9999
      nodePort: 32470
